---
title: "Dimensionality Visualization"
author:
- name: David Rach
  affiliation: University of Maryland, Baltimore
  email: drach@som.umaryland.edu
package: Luciernaga
output:
  BiocStyle::html_document
abstract: |
  How to set up Luciernaga
vignette: |
  %\VignetteIndexEntry{Getting Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

# Getting Started

## Load Libraries
```{r, echo=FALSE, results = "hide", warning=FALSE}
suppressPackageStartupMessages({
library(Luciernaga)
library(flowCore)
library(flowWorkspace)
library(openCyto)
library(ggcyto)  
library(data.table)
library(dplyr)
library(purrr) 
library(stringr)
library(ggplot2)
library(gt)
library(plotly)
library(htmltools)
})
```

```{r Load Libraries}
library(Luciernaga)
library(flowCore)
library(flowWorkspace)
library(openCyto)
library(ggcyto)  
library(data.table)
library(dplyr)
library(purrr) 
library(stringr)
library(ggplot2)
library(gt)
library(plotly)
library(htmltools)
```

## Create a GatingSet

```{r Access Package Data}
File_Location <- system.file("extdata", package = "Luciernaga")
FCS_Pattern <- ".fcs$"
FCS_Files <- list.files(path = File_Location, pattern = FCS_Pattern, full.names = TRUE, recursive = FALSE)
FCS_Files
```

```{r Selecting Desired Files}
SubsetFCSFiles <- FCS_Files[c(1:2, 6)]
SubsetFCSFiles
```

```{r}
MyCytoSet <- load_cytoset_from_fcs(SubsetFCSFiles, truncate_max_range = FALSE, transform = FALSE)
MyCytoSet
MyGatingSet <- GatingSet(MyCytoSet)
MyGatingSet
```

```{r}
FileLocation <- system.file("extdata", package = "Luciernaga")
MyGates <- fread(file.path(path = FileLocation, pattern = 'Gates.csv'))
gt(MyGates)
```

```{r, echo=FALSE, results="FALSE"}
MyGatingTemplate <- gatingTemplate(MyGates)
gt_gating(MyGatingTemplate, MyGatingSet)
MyGatingSet[[1]]
```

## Creating a Gating Set Unmixed

```{r}
UnmixedFCSFiles <- FCS_Files[c(3:5)]
UnmixedFCSFiles
```

```{r}
UnmixedCytoSet <- load_cytoset_from_fcs(UnmixedFCSFiles, truncate_max_range = FALSE, transform = FALSE)
UnmixedGatingSet <- GatingSet(UnmixedCytoSet)
UnmixedGatingSet
```

```{r}
Markers <- colnames(UnmixedCytoSet)
KeptMarkers <- Markers[-grep("Time|FS|SC|SS|Original|-W$|-H$|AF", Markers)]

MyBiexponentialTransform <- flowjo_biexp_trans(channelRange = 256, maxValue = 1000000, pos = 4.5, neg = 0, widthBasis = -1000)
TransformList <- transformerList(KeptMarkers, MyBiexponentialTransform)
UnmixedGatingSet <- transform(UnmixedGatingSet, TransformList)

FileLocation <- system.file("extdata", package = "Luciernaga")
UnmixedGates <- fread(file.path(path = FileLocation, pattern = 'GatesUnmixed.csv'))
UnmixedGating <- gatingTemplate(UnmixedGates)
gt_gating(UnmixedGating, UnmixedGatingSet)
```

## Utility_tSNE

```{r}
Markers <- colnames(MyCytoSet)
KeptMarkers <- Markers[-grep("Time|FS|SC|SS|Original|-W$|-H$|AF", Markers)]
KeptMarkers

pData(MyGatingSet[[3]]) %>% pull(name)
nrow(MyGatingSet[[3]])
plot(MyGatingSet)

tSNE_Output <- Utility_tSNE(x=MyGatingSet[[3]], sample.name = "GUID", removestrings=c("_Cells", ".fcs"), subset = "lymphocytes", columns=KeptMarkers, export=FALSE)

cf <- flowFrame_to_cytoframe(tSNE_Output)
TheNewCS <- cytoset()
cs_add_cytoframe(cs=TheNewCS, sn="Test", cf=cf)
NewGatingSet <- GatingSet(TheNewCS)

TSNEPlot <-  Utility_ThirdColorPlots(x=NewGatingSet[[1]], subset = "root", xaxis="tSNE_1", yaxis = "tSNE_2",  zaxis ="V7-A", splitpoint = "continuous", sample.name = "TUBENAME", removestrings = c("Dimensionality", ".fcs"), thecolor = "orange", tilesize = 0.6)

TSNEPlot 
```


```{r}
Markers <- colnames(UnmixedCytoSet)
KeptMarkers <- Markers[-grep("Time|FS|SC|SS|Original|-W$|-H$|AF", Markers)]
SubsetMarkers <- c("BUV496-A", "BUV805-A", "Pacific Blue-A", "BV711-A",
                       "BV786-A", "Spark Blue 550-A", "PE-A", "APC-Fire 750-A")

pData(UnmixedGatingSet[[3]]) %>% pull(name)
nrow(UnmixedGatingSet[[3]])
plot(UnmixedGatingSet)

removestrings <- c(".fcs")

tSNE_Output <- Utility_tSNE(x=UnmixedGatingSet[[3]], sample.name = "TUBENAME", removestrings=removestrings, subset = "live", columns=SubsetMarkers, export=FALSE)

#BUGGED: flowCore_$P42Rmax not contained in Text section!

cf <- flowFrame_to_cytoframe(tSNE_Output)
TheNewCS <- cytoset()
cs_add_cytoframe(cs=TheNewCS, sn="Test", cf=cf)
NewGatingSet <- GatingSet(TheNewCS)

Sample_TSNEPlot <-  Utility_ThirdColorPlots(x=NewGatingSet[[1]], subset = "root", xaxis="tSNE_1", yaxis = "tSNE_2",  zaxis ="Spark Blue 550-A", splitpoint = "continuous", sample.name = "GROUPNAME", removestrings = removestrings, thecolor = "orange", tilesize = 0.6)

Sample_TSNEPlot 
```

## Utility_UMAP

```{r}
Markers <- colnames(MyCytoSet)
KeptMarkers <- Markers[-grep("Time|FS|SC|SS|Original|-W$|-H$|AF", Markers)]
KeptMarkers

pData(MyGatingSet[[3]]) %>% pull(name)
nrow(MyGatingSet[[3]])
plot(MyGatingSet)

UMAP_Output <- Utility_UMAP(x=MyGatingSet[[3]], sample.name="GUID", removestrings=c("_Cells", ".fcs"), subset="lymphocytes", columns=KeptMarkers, export=FALSE)

cf <- flowFrame_to_cytoframe(UMAP_Output)
TheNewCS <- cytoset()
cs_add_cytoframe(cs=TheNewCS, sn="Test", cf=cf)
NewGatingSet <- GatingSet(TheNewCS)

UMAPPlot <-  Utility_ThirdColorPlots(x=NewGatingSet[[1]], subset = "root", xaxis="UMAP_1", yaxis = "UMAP_2",  zaxis ="V7-A", splitpoint = "continuous", sample.name = "TUBENAME", removestrings = c("Dimensionality", ".fcs"), thecolor = "orange", tilesize = 0.3)

UMAPPlot
```


```{r sessionInfo, echo = FALSE}
sessionInfo()
```


