#' Takes the dataframe generated from CytekQCFilePrep and returns all the QC plots
#'
#' @param x  The data frame object of Aurora QC data generated by CytekQCFilePrep
#' @param FailedFlag Whether to show red flags when a detectors "Out-of-Range" is TRUE
#' @param MeasurementType A list containing character values, will select any present from the column names for plotting
#' @param pdf Whether to return a pdf
#' @param path Location path to return the pdf
#' @param filename File name to save as.
#'
#' @importFrom dplyr select
#' @importFrom tidyr starts_with
#' @importFrom tidyselect contains
#' @importFrom purrr map
#' @importFrom stringr str_detect
#' @importFrom patchwork wrap_plots
#' @importFrom ggplot2 ggplot
#'
#' @return The pdf and/the plots.
#' @export
#'
#' @examples NULL

CytekQCPlots <- function(x, FailedFlag, MeasurementType=NULL, pdf, path, filename){

  if (!is.null(MeasurementType)){
  x <- x %>% select(DateTime, contains(MeasurementType))
  }

  Flagged <- x %>% select(starts_with("Flag"))
  Regular <- x %>% select(-starts_with("Flag"))
  ReorderedData <- cbind(Regular, Flagged)
  FlaggedStart <- length(Regular)+1
  FlaggedEnd <- length(ReorderedData)
  RegularStop <- length(Regular)
  DFNames <- colnames(ReorderedData[2:RegularStop])
  xValue <- colnames(ReorderedData[1])
  PlotNumber <- length(Regular)-1

  StorageLocation <- file.path(path, filename)

  Plots <- map(.x=DFNames, .f = Internal_LevyJennings, FailedFlag = FailedFlag, xValue=xValue, TheData=ReorderedData)

  if (pdf == TRUE){
    AssembledPlots <- Utility_Patchwork(x=Plots, filename=AggregateName, outfolder=outpath, returntype = "pdf")
  } else {
    AssembledPlots <- Utility_Patchwork(x=Plots, filename=AggregateName, outfolder=outpath, returntype = "patchwork")
  }

  return(AssembledPlots)
}


