# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_Luciernaga_wrappers", use_symbols = TRUE, package_name = "Luciernaga")

#' @usage NULL
#' @useDynLib Luciernaga, .registration = TRUE
NULL

#' Verify the matrix type works
#' @export
#' @noRd
describe_matrix <- function(matrix) invisible(.Call(wrap__describe_matrix, matrix))

#' Verify the vector type works
#' @export
#' @noRd
describe_vector <- function(vector) invisible(.Call(wrap__describe_vector, vector))

#' Perform nnls in Rust, return object to R. 
#' @export
#' @noRd
nnls_rust <- function(matrix, vector) .Call(wrap__nnls_rust, matrix, vector)

#' Perform nnls in Rust, return object to R. 
#' @export
#' @noRd
nnls_rust2 <- function(matrix, vector) .Call(wrap__nnls_rust2, matrix, vector)


# nolint end
