utils::globalVariables(c("%rCV", ".", ".data", "AdjustedY", "AggregateName",
                         "Area Scaling Factor", "Averaged", "Backups", "Baseline",
                         "Brightness", "CellRatio_Retained", "Cluster", "Clusters",
                          "ColorSelection", "Column", "ConcentrationScientific",
                         "Condition", "Count", "Counts", "Creator",
                         "CurrentConcentration", "DATE", "Date", "DateTime", "Decision",
                         "DeltaGain", "DesiredConcentration", "Detector", "Detector1Raw",
                         "Detectors", "Experiment", "Fluorochrome", "Fluorophore",
                         "Fluors", "Freq", "From", "Gain", "GainFlag", "Gain_Logical",
                          "IncreaseVolumeML", "Instrument", "Laser", "Laser Delay",
                         "Laser Power", "Ligand", "LostRatio", "LowerLimit_MillionCells",
                         "MainDetector", "NewID", "Partition", "Percentiles", "QCStatus",
                         "RCVFlag", "RankImportance", "RankValue", "Ratio", "Sample",
                          "Specimen", "SpinDown", "Splitpoint", "Summed", "TIME",
                         "TheDetector", "TheDetectors", "TheHeight", "TheInstrumentCount",
                         "TheMedian", "TheSampleName", "TheSamples", "TheSums",
                         "Theoretical", "Time", "Timepoint", 'To', "TotalCells",
                         "TotalTubes", "TotalVolume", "Type", "Var1", "Var2",
                         "cell_fill", "cell_text", "cols_label", "cutoff", "dims",
                          "matches", "name", "opt_table_outline", "parent",
                         "px", "rCV", "rCV_Logical", "regular_split", "specimen",
                         "tab_options", "tags", "value", "x", "xlim", "yhat",
                         "ylim", "pData<-", "parameters<-"))