#' Takes the dataframe generated from CytekQCFilePrep and returns all the QC plots
#'
#' @param x  The data frame object of Aurora QC data generated by CytekQCFilePrep
#' @param FailedFlag Whether to show red flags when a detectors "Out-of-Range" is TRUE
#' @param MeasurementType A list containing character values, will select any present
#' from the column names for plotting
#' @param Metadata An optional character column to use as ggplot factor.
#' @param plotType Whether to return "individual" plots or "comparison" plots (provide Metadata name!)
#' @param returntype Whether to return to pdf, patchwork or plots.
#' @param path Location path to return the pdf
#' @param filename File name to save as.
#' @param thecolumns The number of columns per page
#' @param therows The number of rows per page
#' @param width Desired page width
#' @param height Desired page height
#' @param strict Default FALSE, when TRUE, parameters must be exact match for MeasurementType
#' rather than simply containing those character strings.
#' @param YAxisLabel Character string for the y-axis label.
#' @param RepairVisits Passed data.frame of engineer visits for vertical lines, default NULL.
#'
#' @importFrom dplyr select
#' @importFrom tidyselect contains
#' @importFrom stringr str_detect
#' @importFrom dplyr relocate
#' @importFrom lubridate ymd_hms
#' @importFrom dplyr mutate
#' @importFrom lubridate ymd
#' @importFrom lubridate hms
#' @importFrom tidyr starts_with
#' @importFrom purrr map
#' @importFrom patchwork wrap_plots
#' @importFrom ggplot2 ggplot
#' @importFrom lubridate days
#' @importFrom utils read.csv
#' @importFrom lubridate mdy
#' @importFrom dplyr pull
#' @importFrom dplyr slice
#' @importFrom dplyr arrange
#'
#' @return The pdf and/the plots.
#' @export
#'
#' @examples
#' library(ggplot2)
#'
#' File_Location <- system.file("extdata", package = "Luciernaga")
#' CSV_Pattern <- ".CSV$"
#' CSV_Files <- list.files(path=File_Location, pattern=CSV_Pattern,
#'                        full.names=TRUE)
#' TidyData <- QC_FilePrep(CSV_Files, TrackChange = FALSE)
#'
#' StorageLocation <- file.path("C:", "Users", "JohnDoe", "Desktop")
#'
#' SinglePlot <- "UV7-Gain"
#'
#' TheSinglePlot <- QC_Plots(x = TidyData, MeasurementType = SinglePlot,
#'                          FailedFlag = TRUE, returntype="patchwork",
#'                          path=StorageLocation, filename="CytekAurora5L_QC")

QC_Plots <- function(x, FailedFlag, MeasurementType=NULL, Metadata = NULL,
                     plotType = "individual", returntype, path, filename,
                     thecolumns=1, therows=3, width=7, height=9, strict=FALSE,
                     YAxisLabel=NULL, RepairVisits = NULL){

  # Select or Create DateTime
  if (any(str_detect(colnames(x), "DateTime"))){
    TheDateTime <- x %>% relocate(DateTime, .before=1)
    TheDateTime[["DateTime"]] <- lubridate::ymd_hms(x[["DateTime"]])
  } else {TheDateTime <- x %>% mutate(DateTime = ymd(DATE) + hms(TIME)) %>% relocate(DateTime, .before=1)
  #TheDateTime[["DateTime"]] <- lubridate::ymd_hms(x[["DateTime"]])
  }

  # Select Date Time and Optional Metadata
  if(!is.null(Metadata)){TheDateTime <- TheDateTime %>% select(DateTime, contains(Metadata))
  } else {TheDateTime <- TheDateTime %>% select(DateTime)}

  if(!is.null(RepairVisits)){
    if (!is.data.frame(RepairVisits)){Visit <- read.csv(RepairVisits, check.names=FALSE)
    } else {Visit <- RepairVisits}

    Earliest <- TheDateTime %>% arrange(DateTime) %>% slice(1) %>% pull(DateTime)
    Earliest <- Earliest - days(1)
    Earliest

    Visit$date <- lubridate::mdy(Visit$date)
    TimeWindow <- Visit %>% filter(date > Earliest)
    TheEngineerVisits <- TimeWindow %>% pull(date)
  } else {TheEngineerVisits <- NULL}

  # Select Optional Columns
  if (!is.null(MeasurementType)){
  x <- x %>% select(contains(MeasurementType))
  }

  x <- x %>%
    mutate(across(starts_with("Flag"), ~ as.logical(.)))

  # Remove Any Retained Character Columns
  x <- x %>% select(where( ~ !is.character(.)))

  if (strict == TRUE){
    Regular <- x %>% select(all_of(MeasurementType))
    EquivalentFlags <- paste0("Flag-", colnames(Regular))
    if (!plotType == "comparison" && FailedFlag == TRUE){
    Flagged <- x %>% select(all_of(EquivalentFlags))
    ReorderedData <- cbind(Regular, Flagged)
    } else {ReorderedData <- Regular}
  } else{
  Regular <- x %>% select(-starts_with("Flag"))
  Flagged <- x %>% select(starts_with("Flag"))
  ReorderedData <- cbind(Regular, Flagged)
  }

  FlaggedStart <- length(Regular)+1
  FlaggedEnd <- length(ReorderedData)
  RegularStop <- length(Regular)
  DFNames <- colnames(ReorderedData[seq_len(RegularStop)])

  #Reassemble the data.frame
  TheData <- cbind(TheDateTime, ReorderedData)

  if (is.null(TheEngineerVisits)) {
    Plots <- map(.x=DFNames, .f = LevyJennings, FailedFlag = FailedFlag, xValue="DateTime",
                 TheData=TheData, Metadata=Metadata, plotType=plotType, YAxisLabel=YAxisLabel,
                 EngineerVisits=NULL)
  } else if (length(TheEngineerVisits) > 0){
    Plots <- map(.x=DFNames, .f = LevyJennings, FailedFlag = FailedFlag, xValue="DateTime",
                 TheData=TheData, Metadata=Metadata, plotType=plotType, YAxisLabel=YAxisLabel,
                 EngineerVisits=TheEngineerVisits)
  } else {
    Plots <- map(.x=DFNames, .f = LevyJennings, FailedFlag = FailedFlag, xValue="DateTime",
                       TheData=TheData, Metadata=Metadata, plotType=plotType, YAxisLabel=YAxisLabel,
                       EngineerVisits=NULL)
  }


  if (returntype == "pdf"){
    if(is.null(path)){path <- getwd()}

    AssembledPlots <- Utility_Patchwork(x=Plots, filename=filename, outfolder=path, returntype = "pdf",
                                        thecolumns=thecolumns, therows = therows, width=width, height=height)
  }

  if (returntype == "patchwork"){
    AssembledPlots <- Utility_Patchwork(x=Plots, filename=filename, outfolder=path, returntype = "patchwork",
                                        thecolumns=thecolumns, therows = therows, width=width, height=height)
  }

  if (returntype == "plots"){
    AssembledPlots <- Plots
  }

  return(AssembledPlots)
}

