#' Takes the dataframe generated from CytekQCFilePrep and returns all the QC plots
#'
#' @param x  The data frame object of Aurora QC data generated by CytekQCFilePrep
#' @param FailedFlag Whether to show red flags when a detectors "Out-of-Range" is TRUE
#' @param MeasurementType A list containing character values, will select any present
#' from the column names for plotting
#' @param Metadata An optional character column to use as ggplot factor.
#' @param plotType Whether to return "individual" plots or "comparison" plots (provide Metadata name!)
#' @param returntype Whether to return to pdf, patchwork or plots.
#' @param path Location path to return the pdf
#' @param filename File name to save as.
#' @param thecolumns The number of columns per page
#' @param therows The number of rows per page
#' @param width Desired page width
#' @param height Desired page height
#'
#' @importFrom dplyr select
#' @importFrom tidyselect contains
#' @importFrom stringr str_detect
#' @importFrom dplyr relocate
#' @importFrom lubridate ymd_hms
#' @importFrom dplyr mutate
#' @importFrom lubridate ymd
#' @importFrom lubridate hms
#' @importFrom tidyr starts_with
#' @importFrom purrr map
#' @importFrom patchwork wrap_plots
#' @importFrom ggplot2 ggplot
#'
#' @return The pdf and/the plots.
#' @export
#'
#' @examples NULL

QC_Plots <- function(x, FailedFlag, MeasurementType=NULL, Metadata = NULL, plotType = "individual",
                     returntype, path, filename, thecolumns=1, therows=3, width=7, height=9){

  # Select or Create DateTime
  if (any(str_detect(colnames(x), "DateTime"))){
    TheDateTime <- x %>% relocate(DateTime, .before=1)
    TheDateTime[["DateTime"]] <- lubridate::ymd_hms(x[["DateTime"]])
  } else {TheDateTime <- x %>% mutate(DateTime = ymd(DATE) + hms(TIME)) %>% relocate(DateTime, .before=1)
  TheDateTime[["DateTime"]] <- lubridate::ymd_hms(x[["DateTime"]])}

  # Select Date Time and Optional Metadata
  if(!is.null(Metadata)){TheDateTime <- TheDateTime %>% select(DateTime, contains(Metadata))
  } else {TheDateTime <- TheDateTime %>% select(DateTime)}

  # Select Optional Columns
  if (!is.null(MeasurementType)){
  x <- x %>% select(contains(MeasurementType))
  }

  # Remove Any Retained Character Columns
  x <- x %>% select(where( ~ !is.character(.)))

  # Select Flag columns (alternate would be contains)
  Regular <- x %>% select(-starts_with("Flag"))
  Flagged <- x %>% select(starts_with("Flag"))
  ReorderedData <- cbind(Regular, Flagged)
  FlaggedStart <- length(Regular)+1
  FlaggedEnd <- length(ReorderedData)
  RegularStop <- length(Regular)
  DFNames <- colnames(ReorderedData[1:RegularStop])

  #Reassemble the data.frame
  TheData <- cbind(TheDateTime, ReorderedData)

  Plots <- map(.x=DFNames, .f = LevyJennings, FailedFlag = FailedFlag, xValue="DateTime",
               TheData=TheData, Metadata=Metadata, plotType=plotType)

  if (returntype == "pdf"){
    if(is.null(path)){path <- getwd()}

    AssembledPlots <- Utility_Patchwork(x=Plots, filename=filename, outfolder=path, returntype = "pdf",
                                        thecolumns=thecolumns, therows = therows, width=width, height=height)
  }

  if (returntype == "patchwork"){
    AssembledPlots <- Utility_Patchwork(x=Plots, filename=filename, outfolder=path, returntype = "patchwork",
                                        thecolumns=thecolumns, therows = therows, width=width, height=height)
  }

  if (returntype == "plots"){
    AssembledPlots <- Plots
  }

  return(AssembledPlots)
}

#' Internal for CytekQCPlots
#'
#' @param x  The passed column name to be plotted
#' @param FailedFlag Whether to show red flags when a detectors "Out-of-Range" is TRUE
#' @param xValue The x-axis column plotted by, default is "DateTime"
#' @param TheData The passed data.frame from which to retrieve data
#' @param Metadata The optional column name to be used for "comparison"
#' @param plotType Whether to look "individual" or "comparison"
#'
#' @importFrom dplyr select
#' @importFrom tidyr starts_with
#' @importFrom stringr str_detect
#' @importFrom patchwork wrap_plots
#' @importFrom ggplot2 ggplot
#' @importFrom lubridate ymd_hms
#'
#' @return The pdf and/the plots.
#'
#' @noRd
LevyJennings <- function(x, FailedFlag, xValue, TheData, Metadata, plotType){
  yValue <- x

  # Select Equivalent Flag Column
  if (FailedFlag == TRUE){
    FlagValue <- paste0("Flag-", yValue)
    FlagColumn <- TheData %>% select(starts_with(FlagValue)) %>% colnames(.)
    if (length(FlagColumn) >1){
      NewFlagColumn <- str_detect(FlagColumn, paste0("^", FlagValue, "$"))
      FlagColumn <- FlagColumn[which(NewFlagColumn)]
    } else (FlagColumn <- FlagColumn)
  }

  if (str_detect(yValue, "^UV\\d{1,2}-[A-Za-z]+(_Gain)?$")){
    mycolor <- "purple"
  } else if (str_detect(yValue, "^V\\d{1,2}-[A-Za-z]+(_Gain)?$")){
    mycolor <- "violet"
  } else if (str_detect(yValue, "^B\\d{1,2}-[A-Za-z]+(_Gain)?$")){
    mycolor <- "blue"
  } else if (str_detect(yValue, "^YG\\d{1,2}-[A-Za-z]+(_Gain)?$")){
    mycolor <- "darkgreen"
  } else if (str_detect(yValue, "^R\\d{1,2}-[A-Za-z]+(_Gain)?$")){
    mycolor <- "darkred"
  } else if (str_detect(yValue, "^Change_UV\\d{1,2}(-[A-Za-z% ]+)?$")){
    mycolor <- "purple"
  } else if (str_detect(yValue, "^Change_V\\d{1,2}(-[A-Za-z% ]+)?$")){
    mycolor <- "violet"
  } else if (str_detect(yValue, "^Change_B\\d{1,2}(-[A-Za-z% ]+)?$")){
    mycolor <- "blue"
  } else if (str_detect(yValue, "^Change_YG\\d{1,2}(-[A-Za-z% ]+)?$")){
    mycolor <- "darkgreen"
  } else if (str_detect(yValue, "^Change_R\\d{1,2}(-[A-Za-z% ]+)?$")){
    mycolor <- "darkred"
  } else {mycolor <- "black"}


  if (plotType == "individual"){

    if (FailedFlag == TRUE){

      if (any(grepl("FALSE", TheData[[FlagColumn]]))) {
        shape_qc <- c("FALSE" = 21, "TRUE" = 22)
        fill_qc <- c("FALSE" = mycolor, "TRUE" = "red")
        size_qc <- c("FALSE" = 1, "TRUE" = 3)

      } else {
        shape_qc <- c("False" = 21, "True" = 22)
        fill_qc <- c("False" = mycolor, "True" = "red")
        size_qc <- c("False" = 1, "True" = 3)
      }

      Plot <- ggplot(TheData, aes(x=.data[[xValue]], y = .data[[yValue]]))  +
        geom_line(color = mycolor, linewidth = 1) +  geom_point(aes(
        shape = .data[[FlagColumn]], size = .data[[FlagColumn]],
        fill = .data[[FlagColumn]])) + scale_shape_manual(values = shape_qc) +
        scale_fill_manual(values = fill_qc) + scale_size_manual(values = size_qc) +
        labs(title = yValue, x = NULL, y = "Values") + theme_bw() +
        theme(legend.position = "none")

    } else {Plot <- ggplot(TheData, aes(x=.data[[xValue]], y = .data[[yValue]],
            color = mycolor)) + geom_line(color = mycolor) + geom_point(
            color = mycolor) + labs(title = yValue, x = NULL, y = "Values") +
            theme_bw() + theme(legend.position = "none")
    }
  }

  if (plotType == "comparison"){
    VariantColor <- c("black", mycolor)

    Plot <- ggplot(TheData, aes(x=.data[[xValue]], y = .data[[yValue]], group = .data[[Metadata]],
      color=.data[[Metadata]])) + geom_line(aes(color = .data[[Metadata]])) +
      geom_point(aes(color = .data[[Metadata]])) + scale_color_manual(values = VariantColor) +
      labs(title = yValue, x = NULL, y = "Values") + theme(legend.position = "none") + theme_bw()
  }

  return(Plot)
}
