#' Takes the dataframe generated from CytekQCFilePrep and returns all the QC plots
#'
#' @param x  The data frame object of Aurora QC data generated by CytekQCFilePrep
#' @param FailedFlag Whether to show red flags when a detectors "Out-of-Range" is TRUE
#' @param MeasurementType A list containing character values, will select any present
#' from the column names for plotting
#' @param Metadata An optional character column to use as ggplot factor.
#' @param plotType Whether to return "individual" plots or "comparison" plots (provide Metadata name!)
#' @param returntype Whether to return to pdf, patchwork or plots.
#' @param path Location path to return the pdf
#' @param filename File name to save as.
#' @param thecolumns The number of columns per page
#' @param therows The number of rows per page
#' @param width Desired page width
#' @param height Desired page height
#' @param strict Default FALSE, when TRUE, parameters must be exact match for MeasurementType
#' rather than simply containing those character strings.
#' @param YAxisLabel Character string for the y-axis label.
#' @param RepairVisits Passed data.frame of engineer visits for vertical lines, default NULL.
#'
#' @importFrom dplyr select
#' @importFrom tidyselect contains
#' @importFrom stringr str_detect
#' @importFrom dplyr relocate
#' @importFrom lubridate ymd_hms
#' @importFrom dplyr mutate
#' @importFrom lubridate ymd
#' @importFrom lubridate hms
#' @importFrom tidyr starts_with
#' @importFrom purrr map
#' @importFrom patchwork wrap_plots
#' @importFrom ggplot2 ggplot
#' @importFrom lubridate days
#' @importFrom utils read.csv
#' @importFrom lubridate mdy
#' @importFrom dplyr pull
#' @importFrom dplyr slice
#' @importFrom dplyr arrange
#'
#' @return The pdf and/the plots.
#' @export
#'
#' @examples
#' library(ggplot2)
#'
#' File_Location <- system.file("extdata", package = "Luciernaga")
#' CSV_Pattern <- ".CSV$"
#' CSV_Files <- list.files(path=File_Location, pattern=CSV_Pattern,
#'                        full.names=TRUE)
#' TidyData <- QC_FilePrep(CSV_Files, TrackChange = FALSE)
#'
#' StorageLocation <- file.path("C:", "Users", "JohnDoe", "Desktop")
#'
#' SinglePlot <- "UV7-Gain"
#'
#' TheSinglePlot <- QC_Plots(x = TidyData, MeasurementType = SinglePlot,
#'                          FailedFlag = TRUE, returntype="patchwork",
#'                          path=StorageLocation, filename="CytekAurora5L_QC")

QC_Plots <- function(x, FailedFlag, MeasurementType=NULL, Metadata = NULL,
                     plotType = "individual", returntype, path, filename,
                     thecolumns=1, therows=3, width=7, height=9, strict=FALSE,
                     YAxisLabel=NULL, RepairVisits = NULL){

  # Select or Create DateTime
  if (any(str_detect(colnames(x), "DateTime"))){
    TheDateTime <- x %>% relocate(DateTime, .before=1)
    TheDateTime[["DateTime"]] <- lubridate::ymd_hms(x[["DateTime"]])
  } else {TheDateTime <- x %>% mutate(DateTime = ymd(DATE) + hms(TIME)) %>% relocate(DateTime, .before=1)
  #TheDateTime[["DateTime"]] <- lubridate::ymd_hms(x[["DateTime"]])
  }

  # Select Date Time and Optional Metadata
  if(!is.null(Metadata)){TheDateTime <- TheDateTime %>% select(DateTime, contains(Metadata))
  } else {TheDateTime <- TheDateTime %>% select(DateTime)}

  if(!is.null(RepairVisits)){
    if (!is.data.frame(RepairVisits)){Visit <- read.csv(RepairVisits, check.names=FALSE)
    } else {Visit <- RepairVisits}

    Earliest <- TheDateTime %>% arrange(DateTime) %>% slice(1) %>% pull(DateTime)
    Earliest <- Earliest - days(1)
    Earliest

    Visit$date <- lubridate::mdy(Visit$date)
    TimeWindow <- Visit %>% filter(date > Earliest)
    TheEngineerVisits <- TimeWindow %>% pull(date)
  } else {TheEngineerVisits <- NULL}

  # Select Optional Columns
  if (!is.null(MeasurementType)){
  x <- x %>% select(contains(MeasurementType))
  }

  x <- x %>%
    mutate(across(starts_with("Flag"), ~ as.logical(.)))

  # Remove Any Retained Character Columns
  x <- x %>% select(where( ~ !is.character(.)))

  if (strict == TRUE){
    Regular <- x %>% select(all_of(MeasurementType))
    EquivalentFlags <- paste0("Flag-", colnames(Regular))
    if (!plotType == "comparison"){
    Flagged <- x %>% select(all_of(EquivalentFlags))
    ReorderedData <- cbind(Regular, Flagged)
    } else {ReorderedData <- Regular}
  } else{
  Regular <- x %>% select(-starts_with("Flag"))
  Flagged <- x %>% select(starts_with("Flag"))
  ReorderedData <- cbind(Regular, Flagged)
  }

  FlaggedStart <- length(Regular)+1
  FlaggedEnd <- length(ReorderedData)
  RegularStop <- length(Regular)
  DFNames <- colnames(ReorderedData[1:RegularStop])

  #Reassemble the data.frame
  TheData <- cbind(TheDateTime, ReorderedData)

  if (is.null(TheEngineerVisits)) {
    Plots <- map(.x=DFNames, .f = LevyJennings, FailedFlag = FailedFlag, xValue="DateTime",
                 TheData=TheData, Metadata=Metadata, plotType=plotType, YAxisLabel=YAxisLabel,
                 EngineerVisits=NULL)
  } else if (length(TheEngineerVisits) > 0){
    Plots <- map(.x=DFNames, .f = LevyJennings, FailedFlag = FailedFlag, xValue="DateTime",
                 TheData=TheData, Metadata=Metadata, plotType=plotType, YAxisLabel=YAxisLabel,
                 EngineerVisits=TheEngineerVisits)
  } else {
    Plots <- map(.x=DFNames, .f = LevyJennings, FailedFlag = FailedFlag, xValue="DateTime",
                       TheData=TheData, Metadata=Metadata, plotType=plotType, YAxisLabel=YAxisLabel,
                       EngineerVisits=NULL)
  }


  if (returntype == "pdf"){
    if(is.null(path)){path <- getwd()}

    AssembledPlots <- Utility_Patchwork(x=Plots, filename=filename, outfolder=path, returntype = "pdf",
                                        thecolumns=thecolumns, therows = therows, width=width, height=height)
  }

  if (returntype == "patchwork"){
    AssembledPlots <- Utility_Patchwork(x=Plots, filename=filename, outfolder=path, returntype = "patchwork",
                                        thecolumns=thecolumns, therows = therows, width=width, height=height)
  }

  if (returntype == "plots"){
    AssembledPlots <- Plots
  }

  return(AssembledPlots)
}

#' Internal for CytekQCPlots
#'
#' @param x  The passed column name to be plotted
#' @param FailedFlag Whether to show red flags when a detectors "Out-of-Range" is TRUE
#' @param xValue The x-axis column plotted by, default is "DateTime"
#' @param TheData The passed data.frame from which to retrieve data
#' @param Metadata The optional column name to be used for "comparison"
#' @param plotType Whether to look "individual" or "comparison"
#' @param EngineerVisits Passed data.frame of engineer visits for vertical lines, default NULL.
#'
#' @importFrom dplyr select
#' @importFrom tidyr starts_with
#' @importFrom stringr str_detect
#' @importFrom patchwork wrap_plots
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 theme_bw
#' @importFrom lubridate ymd_hms
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_shape_manual
#' @importFrom ggplot2 scale_size_manual
#' @importFrom ggplot2 geom_vline
#'
#' @return The pdf and/the plots.
#'
#' @noRd
LevyJennings <- function(x, FailedFlag, xValue, TheData, Metadata,
                         plotType, YAxisLabel, EngineerVisits=NULL){

  yValue <- x

  # Select Equivalent Flag Column
  if (FailedFlag == TRUE){
    FlagValue <- paste0("Flag-", yValue)
    FlagColumn <- TheData %>% select(starts_with(FlagValue)) %>% colnames(.)
    if (length(FlagColumn) >1){
      NewFlagColumn <- str_detect(FlagColumn, paste0("^", FlagValue, "$"))
      FlagColumn <- FlagColumn[which(NewFlagColumn)]
    } else (FlagColumn <- FlagColumn)
  }

  if (str_detect(yValue, "^UV\\d{1,2}-[A-Za-z]+(_Gain)?$")){
    mycolor <- "purple"
  } else if (str_detect(yValue, "^V\\d{1,2}-[A-Za-z]+(_Gain)?$")){
    mycolor <- "violet"
  } else if (str_detect(yValue, "^B\\d{1,2}-[A-Za-z]+(_Gain)?$")){
    mycolor <- "blue"
  } else if (str_detect(yValue, "^YG\\d{1,2}-[A-Za-z]+(_Gain)?$")){
    mycolor <- "darkgreen"
  } else if (str_detect(yValue, "^R\\d{1,2}-[A-Za-z]+(_Gain)?$")){
    mycolor <- "darkred"
  } else if (str_detect(yValue, "^Change_UV\\d{1,2}(-[A-Za-z% ]+)?$")){
    mycolor <- "purple"
  } else if (str_detect(yValue, "^Change_V\\d{1,2}(-[A-Za-z% ]+)?$")){
    mycolor <- "violet"
  } else if (str_detect(yValue, "^Change_B\\d{1,2}(-[A-Za-z% ]+)?$")){
    mycolor <- "blue"
  } else if (str_detect(yValue, "^Change_YG\\d{1,2}(-[A-Za-z% ]+)?$")){
    mycolor <- "darkgreen"
  } else if (str_detect(yValue, "^Change_R\\d{1,2}(-[A-Za-z% ]+)?$")){
    mycolor <- "darkred"
  } else {mycolor <- "black"}


  if (plotType == "individual"){

    if (FailedFlag == TRUE){

      if (any(grepl("FALSE", TheData[[FlagColumn]]))) {
        shape_qc <- c("FALSE" = 21, "TRUE" = 22)
        fill_qc <- c("FALSE" = mycolor, "TRUE" = "red")
        size_qc <- c("FALSE" = 1, "TRUE" = 3)

      } else {
        shape_qc <- c("False" = 21, "True" = 22)
        fill_qc <- c("False" = mycolor, "True" = "red")
        size_qc <- c("False" = 1, "True" = 3)
      }

      Plot <- ggplot(TheData, aes(x=.data[[xValue]], y = .data[[yValue]]))  +
        geom_line(color = mycolor, linewidth = 1) +  geom_point(aes(
        shape = .data[[FlagColumn]], size = .data[[FlagColumn]],
        fill = .data[[FlagColumn]])) + scale_shape_manual(values = shape_qc) +
        scale_fill_manual(values = fill_qc) + scale_size_manual(values = size_qc) +
        labs(title = yValue, x = NULL, y = YAxisLabel) + theme_bw() +
        theme(legend.position = "none")

    } else {Plot <- ggplot(TheData, aes(x=.data[[xValue]], y = .data[[yValue]],
            color = mycolor)) + geom_line(color = mycolor) + geom_point(
            color = mycolor) + labs(title = yValue, x = NULL, y = YAxisLabel) +
            theme_bw() + theme(legend.position = "none")

    }
  }

  if (plotType == "comparison"){
    if (mycolor != "black"){VariantColor <- c("black", mycolor)
    } else {VariantColor <- c("gray", mycolor)}

    Plot <- ggplot(TheData, aes(x=.data[[xValue]], y = .data[[yValue]], group = .data[[Metadata]],
      color=.data[[Metadata]])) + geom_line(aes(color = .data[[Metadata]])) +
      geom_point(aes(color = .data[[Metadata]])) + scale_color_manual(values = VariantColor) +
      labs(title = yValue, x = NULL, y = YAxisLabel) + theme(legend.position = "none") + theme_bw()
  }

  if (is.null(EngineerVisits)){
    Plot1 <- Plot
  } else {
    Plot1 <- Plot + geom_vline(xintercept = as.POSIXct(EngineerVisits),
                              color = "red", linetype = "dashed")
  }

  return(Plot1)
}
